@echo off
REM Stage11 environment bootstrap (non-destructive).
REM Usage:
REM   call scripts\activate_stage11_recovery_env.bat

setlocal

set "SCRIPT_DIR=%~dp0"
for %%I in ("%SCRIPT_DIR%..") do set "PROJECT_ROOT=%%~fI"

if not defined PY310_HOME set "PY310_HOME=%PROJECT_ROOT%\..\Python310"
if not exist "%PY310_HOME%\python.exe" set "PY310_HOME=D:\Python310"
if not defined HADOOP_HOME set "HADOOP_HOME=%PROJECT_ROOT%\tools\hadoop"

set "PATH=%PY310_HOME%;%PY310_HOME%\Scripts;%HADOOP_HOME%\bin;%PATH%"
set "PYSPARK_PYTHON=%PY310_HOME%\python.exe"
set "PYSPARK_DRIVER_PYTHON=%PY310_HOME%\python.exe"
set "PYTHONPATH=%PROJECT_ROOT%\scripts;%PYTHONPATH%"

set "SPARK_SUBMIT_OPTS=-Djava.library.path=%HADOOP_HOME%\bin"
set "SPARK_DRIVER_HOST=127.0.0.1"
set "SPARK_DRIVER_BIND_ADDRESS=127.0.0.1"
set "SPARK_MASTER=local[2]"
set "SPARK_DRIVER_MEMORY=6g"
set "SPARK_EXECUTOR_MEMORY=6g"
set "SPARK_SQL_SHUFFLE_PARTITIONS=8"
set "SPARK_DEFAULT_PARALLELISM=8"
set "SPARK_NETWORK_TIMEOUT=600s"
set "SPARK_EXECUTOR_HEARTBEAT_INTERVAL=60s"
set "SPARK_LOCAL_DIR=%PROJECT_ROOT%\data\spark-tmp"

REM Optional override. Keep one stable default run for convenience.
if not defined INPUT_09_RUN_DIR set "INPUT_09_RUN_DIR=%PROJECT_ROOT%\data\output\09_candidate_fusion\20260225_185004_full_stage09_candidate_fusion"

echo [ENV] PROJECT_ROOT=%PROJECT_ROOT%
echo [ENV] PYSPARK_PYTHON=%PYSPARK_PYTHON%
echo [ENV] INPUT_09_RUN_DIR=%INPUT_09_RUN_DIR%
echo [ENV] SPARK_LOCAL_DIR=%SPARK_LOCAL_DIR%
echo [ENV] done

endlocal & (
  set "PROJECT_ROOT=%PROJECT_ROOT%"
  set "PY310_HOME=%PY310_HOME%"
  set "HADOOP_HOME=%HADOOP_HOME%"
  set "PATH=%PATH%"
  set "PYSPARK_PYTHON=%PYSPARK_PYTHON%"
  set "PYSPARK_DRIVER_PYTHON=%PYSPARK_DRIVER_PYTHON%"
  set "PYTHONPATH=%PYTHONPATH%"
  set "SPARK_SUBMIT_OPTS=%SPARK_SUBMIT_OPTS%"
  set "SPARK_DRIVER_HOST=%SPARK_DRIVER_HOST%"
  set "SPARK_DRIVER_BIND_ADDRESS=%SPARK_DRIVER_BIND_ADDRESS%"
  set "SPARK_MASTER=%SPARK_MASTER%"
  set "SPARK_DRIVER_MEMORY=%SPARK_DRIVER_MEMORY%"
  set "SPARK_EXECUTOR_MEMORY=%SPARK_EXECUTOR_MEMORY%"
  set "SPARK_SQL_SHUFFLE_PARTITIONS=%SPARK_SQL_SHUFFLE_PARTITIONS%"
  set "SPARK_DEFAULT_PARALLELISM=%SPARK_DEFAULT_PARALLELISM%"
  set "SPARK_NETWORK_TIMEOUT=%SPARK_NETWORK_TIMEOUT%"
  set "SPARK_EXECUTOR_HEARTBEAT_INTERVAL=%SPARK_EXECUTOR_HEARTBEAT_INTERVAL%"
  set "SPARK_LOCAL_DIR=%SPARK_LOCAL_DIR%"
  set "INPUT_09_RUN_DIR=%INPUT_09_RUN_DIR%"
)
