#!/usr/bin/env bash
set -euo pipefail
# Legacy compatibility launcher. Prefer scripts/launchers/stage09_bucket5_mainline.sh.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
source "${SCRIPT_DIR}/launchers/_path_contract.sh"
PYTHON_BIN="${PYTHON_BIN:-}"
if [[ -z "$PYTHON_BIN" ]]; then
  if command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN="$(command -v python3)"
  elif command -v python >/dev/null 2>&1; then
    PYTHON_BIN="$(command -v python)"
  else
    PYTHON_BIN="${BDA_REMOTE_PYTHON_BIN}"
  fi
fi

OUTPUT_ROOT_DIR="${OUTPUT_ROOT_DIR:-${BDA_REMOTE_PROJECT_OUTPUT_ROOT}/09_candidate_fusion_structural_v5_sourceparity}"
SPARK_LOCAL_DIR="${SPARK_LOCAL_DIR:-${BDA_REMOTE_PROJECT_SPARK_TMP_ROOT}}"
OUTPUT_09_AUDIT_ROOT_DIR="${OUTPUT_09_AUDIT_ROOT_DIR:-${BDA_REMOTE_PROJECT_OUTPUT_ROOT}/09_recall_audit_sourceparity_v5}"
PARQUET_BASE_DIR="${PARQUET_BASE_DIR:-$PROJECT_ROOT/data/parquet}"
AUDIT_USER_COHORT_CSV="${AUDIT_USER_COHORT_CSV:-$PROJECT_ROOT/data/output/09_bucket_roster_diff/20260324_accepted_vs_v5_bucket5/bucket_5_accepted_truth_userid_roster.csv}"

export STAGE09_CLOUD_FAST_MODE="${STAGE09_CLOUD_FAST_MODE:-true}"
export SPARK_MASTER="${SPARK_MASTER:-local[28]}"
export SPARK_DRIVER_MEMORY="${SPARK_DRIVER_MEMORY:-120g}"
export SPARK_EXECUTOR_MEMORY="${SPARK_EXECUTOR_MEMORY:-120g}"
export SPARK_SQL_SHUFFLE_PARTITIONS="${SPARK_SQL_SHUFFLE_PARTITIONS:-192}"
export SPARK_DEFAULT_PARALLELISM="${SPARK_DEFAULT_PARALLELISM:-192}"
export SPARK_NETWORK_TIMEOUT="${SPARK_NETWORK_TIMEOUT:-1200s}"
export SPARK_EXECUTOR_HEARTBEAT_INTERVAL="${SPARK_EXECUTOR_HEARTBEAT_INTERVAL:-120s}"
export SPARK_SQL_ADAPTIVE_ENABLED="${SPARK_SQL_ADAPTIVE_ENABLED:-true}"
export SPARK_SQL_PARQUET_ENABLE_VECTORIZED="${SPARK_SQL_PARQUET_ENABLE_VECTORIZED:-true}"
export SPARK_SQL_FILES_MAX_PARTITION_BYTES="${SPARK_SQL_FILES_MAX_PARTITION_BYTES:-128m}"
export SPARK_DRIVER_EXTRA_JAVA_OPTIONS="${SPARK_DRIVER_EXTRA_JAVA_OPTIONS:--XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:InitiatingHeapOccupancyPercent=35 -XX:ReservedCodeCacheSize=256m -XX:MaxMetaspaceSize=512m -Xss1m}"
export SPARK_EXECUTOR_EXTRA_JAVA_OPTIONS="${SPARK_EXECUTOR_EXTRA_JAVA_OPTIONS:--XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:InitiatingHeapOccupancyPercent=35 -XX:ReservedCodeCacheSize=256m -XX:MaxMetaspaceSize=512m -Xss1m}"
export SPARK_LOCAL_DIR
export SPARK_TMP_SESSION_ISOLATION="${SPARK_TMP_SESSION_ISOLATION:-true}"
export SPARK_TMP_AUTOCLEAN_ENABLED="${SPARK_TMP_AUTOCLEAN_ENABLED:-true}"
export SPARK_TMP_CLEAN_ON_EXIT="${SPARK_TMP_CLEAN_ON_EXIT:-true}"
export SPARK_TMP_RETENTION_HOURS="${SPARK_TMP_RETENTION_HOURS:-8}"
export SPARK_TMP_CLEAN_MAX_ENTRIES="${SPARK_TMP_CLEAN_MAX_ENTRIES:-3000}"
export PYTHONUNBUFFERED=1
export PARQUET_BASE_DIR

export RUN_PROFILE_OVERRIDE="${RUN_PROFILE_OVERRIDE:-full}"
export RECALL_PROFILE_OVERRIDE="${RECALL_PROFILE_OVERRIDE:-coverage_stage2}"
export MIN_TRAIN_BUCKETS_OVERRIDE="${MIN_TRAIN_BUCKETS_OVERRIDE:-5}"
export OUTPUT_ROOT_DIR
export OUTPUT_09_AUDIT_ROOT_DIR
export WRITE_TRUTH_USER_ROSTER="${WRITE_TRUTH_USER_ROSTER:-true}"

export ENABLE_CONTEXT_SURFACE="${ENABLE_CONTEXT_SURFACE:-true}"
export CONTEXT_SURFACE_BUCKETS="${CONTEXT_SURFACE_BUCKETS:-5}"
export CONTEXT_SURFACE_TOP_K="${CONTEXT_SURFACE_TOP_K:-120}"
export CONTEXT_SURFACE_SCORE_MIN="${CONTEXT_SURFACE_SCORE_MIN:-0.12}"
export CONTEXT_SURFACE_BATCH_USERS="${CONTEXT_SURFACE_BATCH_USERS:-256}"

export ENABLE_PROFILE_MULTIVECTOR_ROUTE_INTEGRATION="${ENABLE_PROFILE_MULTIVECTOR_ROUTE_INTEGRATION:-true}"
export PROFILE_MULTIVECTOR_ROUTE_INTEGRATION_BUCKETS="${PROFILE_MULTIVECTOR_ROUTE_INTEGRATION_BUCKETS:-5}"
export PROFILE_MULTIVECTOR_ROUTE_INTEGRATION_TOP_K="${PROFILE_MULTIVECTOR_ROUTE_INTEGRATION_TOP_K:-120}"
export PROFILE_MULTIVECTOR_ROUTE_INTEGRATION_SCORE_MIN="${PROFILE_MULTIVECTOR_ROUTE_INTEGRATION_SCORE_MIN:-0.18}"
export PROFILE_MULTIVECTOR_ROUTE_INTEGRATION_BATCH_USERS="${PROFILE_MULTIVECTOR_ROUTE_INTEGRATION_BATCH_USERS:-128}"

export PRETRIM_TOP_K_OVERRIDE="${PRETRIM_TOP_K_OVERRIDE:-480}"
export PRETRIM_SEGMENT_TOPK_BY_BUCKET_JSON="${PRETRIM_SEGMENT_TOPK_BY_BUCKET_JSON:-{\"5\":{\"light\":430,\"mid\":500,\"heavy\":640,\"unknown\":430}}}"
export TOWER_SEQ_HEAD_WINDOW_BY_BUCKET_JSON="${TOWER_SEQ_HEAD_WINDOW_BY_BUCKET_JSON:-{\"5\":250}}"

export ENABLE_PERSONALIZED_CHALLENGER_SURFACE="${ENABLE_PERSONALIZED_CHALLENGER_SURFACE:-true}"
export PERSONALIZED_CHALLENGER_BUCKETS="${PERSONALIZED_CHALLENGER_BUCKETS:-5}"
export PERSONALIZED_CHALLENGER_QUOTA="${PERSONALIZED_CHALLENGER_QUOTA:-72}"
export PERSONALIZED_CHALLENGER_MAX_PRE_RANK="${PERSONALIZED_CHALLENGER_MAX_PRE_RANK:-320}"
export PERSONALIZED_CHALLENGER_HEAD_WINDOW="${PERSONALIZED_CHALLENGER_HEAD_WINDOW:-250}"
export PERSONALIZED_CHALLENGER_MAX_POP_COUNT="${PERSONALIZED_CHALLENGER_MAX_POP_COUNT:-170}"
export PERSONALIZED_CHALLENGER_MIN_MV_ROUTES="${PERSONALIZED_CHALLENGER_MIN_MV_ROUTES:-1}"
export PERSONALIZED_CHALLENGER_MIN_PROFILE_CLUSTER="${PERSONALIZED_CHALLENGER_MIN_PROFILE_CLUSTER:-1}"
export PERSONALIZED_CHALLENGER_MIN_NONPOPULAR_SOURCES="${PERSONALIZED_CHALLENGER_MIN_NONPOPULAR_SOURCES:-1}"
export PERSONALIZED_CHALLENGER_MIN_SEMANTIC_SCORE="${PERSONALIZED_CHALLENGER_MIN_SEMANTIC_SCORE:-0.81}"
export PERSONALIZED_CHALLENGER_EXCLUDE_POPULAR="${PERSONALIZED_CHALLENGER_EXCLUDE_POPULAR:-false}"

export ENABLE_PROFILE_EVIDENCE_PROTECTED_LANE="${ENABLE_PROFILE_EVIDENCE_PROTECTED_LANE:-true}"
export PROFILE_EVIDENCE_PROTECTED_LANE_BUCKETS="${PROFILE_EVIDENCE_PROTECTED_LANE_BUCKETS:-5}"
export PROFILE_EVIDENCE_PROTECTED_LANE_QUOTA="${PROFILE_EVIDENCE_PROTECTED_LANE_QUOTA:-56}"
export PROFILE_EVIDENCE_PROTECTED_LANE_MAX_PRE_RANK="${PROFILE_EVIDENCE_PROTECTED_LANE_MAX_PRE_RANK:-300}"
export PROFILE_EVIDENCE_PROTECTED_LANE_MAX_POP_COUNT="${PROFILE_EVIDENCE_PROTECTED_LANE_MAX_POP_COUNT:-140}"
export PROFILE_EVIDENCE_PROTECTED_LANE_MIN_MV_ROUTES="${PROFILE_EVIDENCE_PROTECTED_LANE_MIN_MV_ROUTES:-1}"
export PROFILE_EVIDENCE_PROTECTED_LANE_MIN_SEMANTIC_SCORE="${PROFILE_EVIDENCE_PROTECTED_LANE_MIN_SEMANTIC_SCORE:-0.83}"
export PROFILE_EVIDENCE_PROTECTED_LANE_MIN_PROFILE_CLUSTER="${PROFILE_EVIDENCE_PROTECTED_LANE_MIN_PROFILE_CLUSTER:-1}"
export PROFILE_EVIDENCE_PROTECTED_LANE_EXCLUDE_POPULAR="${PROFILE_EVIDENCE_PROTECTED_LANE_EXCLUDE_POPULAR:-false}"

export LAYERED_PRETRIM_BY_BUCKET_JSON="${LAYERED_PRETRIM_BY_BUCKET_JSON:-{\"5\":{\"front_guard_topk\":145,\"rescue_quota\":24,\"rescue_max_pre_rank\":440,\"rescue_min_nonpopular_sources\":1,\"rescue_profile_cluster_min\":1,\"rescue_als_rank_max\":300,\"rescue_cluster_rank_max\":200,\"rescue_profile_rank_max\":200,\"l1_quota\":280,\"l2_quota\":210,\"l3_quota\":140,\"l1_als_rank_max\":130,\"l1_cluster_rank_max\":85,\"l1_profile_rank_max\":85,\"l2_als_rank_max\":420,\"l2_cluster_rank_max\":280,\"l2_profile_rank_max\":280}}}"
export PRETRIM_HEAD_POLICY_JSON="${PRETRIM_HEAD_POLICY_JSON:-{\"5\":{\"source_count_weight\":0.018,\"source_count_cap\":2,\"multi_source_min\":2,\"profile_rank_weight\":0.038,\"profile_rank_cap\":180,\"cluster_rank_weight\":0.022,\"cluster_rank_cap\":180,\"popular_only_penalty\":0.015}}}"
if [[ -z "${SOURCE_WEIGHTS_BY_BUCKET_JSON:-}" ]]; then
  export SOURCE_WEIGHTS_BY_BUCKET_JSON='{"5":{"light":{"als":0.41,"cluster":0.22,"popular":0.12,"profile":0.18,"context":0.16},"mid":{"als":0.63,"cluster":0.12,"popular":0.05,"profile":0.10,"context":0.12},"heavy":{"als":0.78,"cluster":0.06,"popular":0.02,"profile":0.07,"context":0.06}}}'
else
  export SOURCE_WEIGHTS_BY_BUCKET_JSON
fi

mkdir -p "$OUTPUT_ROOT_DIR" "$OUTPUT_09_AUDIT_ROOT_DIR" "$SPARK_LOCAL_DIR"

echo "[INFO] stage09 bucket5 structural v5 sourceparity launcher"
echo "[INFO] PYTHON_BIN=$PYTHON_BIN"
echo "[INFO] OUTPUT_ROOT_DIR=$OUTPUT_ROOT_DIR"
echo "[INFO] PARQUET_BASE_DIR=$PARQUET_BASE_DIR"
echo "[INFO] AUDIT_USER_COHORT_CSV=$AUDIT_USER_COHORT_CSV"
echo "[INFO] SPARK_MASTER=$SPARK_MASTER DRIVER=$SPARK_DRIVER_MEMORY EXECUTOR=$SPARK_EXECUTOR_MEMORY"

"$PYTHON_BIN" "$PROJECT_ROOT/scripts/09_candidate_fusion.py"

RUN_DIR="$(ls -dt "$OUTPUT_ROOT_DIR"/*_stage09_candidate_fusion 2>/dev/null | head -n 1)"
if [[ -z "$RUN_DIR" ]]; then
  echo "[ERROR] no stage09 run found under $OUTPUT_ROOT_DIR" >&2
  exit 1
fi
echo "[INFO] stage09 run dir=$RUN_DIR"

export INPUT_09_RUN_DIR="$RUN_DIR"
export AUDIT_USER_COHORT_CSV
"$PYTHON_BIN" "$PROJECT_ROOT/scripts/09_1_recall_audit.py"
