#!/usr/bin/env bash
set -euo pipefail

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  echo "Usage: bash scripts/runtime_sh/run_stage11_persona_sft_v3_qwen35_35b_a3b_probe.sh"
  echo "Runs a Qwen3.5-35B-A3B Stage11 persona SFT probe. This is a cloud/GPU training job."
  echo "Set remote model and project paths, then run without --help."
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"

export RUN_TAG="${RUN_TAG:-stage11_2_persona_sft_train_v3_qwen35_35b_a3b_probe}"
export PERSONA_SFT_BASE_MODEL="${PERSONA_SFT_BASE_MODEL:-/root/autodl-tmp/models/Qwen3.5-35B-A3B-Base}"
export PERSONA_SFT_USE_4BIT="${PERSONA_SFT_USE_4BIT:-false}"
export PERSONA_SFT_USE_BF16="${PERSONA_SFT_USE_BF16:-true}"
export PERSONA_SFT_ATTN_IMPL="${PERSONA_SFT_ATTN_IMPL:-flash_attention_2}"
export PERSONA_SFT_DISABLE_GROUPED_MM="${PERSONA_SFT_DISABLE_GROUPED_MM:-true}"
export PERSONA_SFT_MAX_SEQ_LEN="${PERSONA_SFT_MAX_SEQ_LEN:-6144}"
export PERSONA_SFT_MAX_STEPS="${PERSONA_SFT_MAX_STEPS:-75}"
export PERSONA_SFT_MAX_TRAIN_ROWS="${PERSONA_SFT_MAX_TRAIN_ROWS:-0}"
export PERSONA_SFT_MAX_EVAL_ROWS="${PERSONA_SFT_MAX_EVAL_ROWS:-0}"
export PERSONA_SFT_LR="${PERSONA_SFT_LR:-3e-5}"
export PERSONA_SFT_BATCH_SIZE="${PERSONA_SFT_BATCH_SIZE:-1}"
export PERSONA_SFT_EVAL_BATCH_SIZE="${PERSONA_SFT_EVAL_BATCH_SIZE:-1}"
export PERSONA_SFT_GRAD_ACC="${PERSONA_SFT_GRAD_ACC:-8}"
export PERSONA_SFT_LORA_R="${PERSONA_SFT_LORA_R:-16}"
export PERSONA_SFT_LORA_ALPHA="${PERSONA_SFT_LORA_ALPHA:-32}"
export PERSONA_SFT_OPTIMIZER="${PERSONA_SFT_OPTIMIZER:-adamw_torch}"
export PERSONA_SFT_SAVE_STEPS="${PERSONA_SFT_SAVE_STEPS:-75}"
export PERSONA_SFT_EVAL_STEPS="${PERSONA_SFT_EVAL_STEPS:-75}"
export PERSONA_SFT_LOGGING_STEPS="${PERSONA_SFT_LOGGING_STEPS:-5}"
export PERSONA_SFT_GEN_EVAL_ROWS="${PERSONA_SFT_GEN_EVAL_ROWS:-24}"
export PERSONA_SFT_GEN_MAX_NEW_TOKENS="${PERSONA_SFT_GEN_MAX_NEW_TOKENS:-1024}"
export PERSONA_SFT_GEN_BATCH_SIZE="${PERSONA_SFT_GEN_BATCH_SIZE:-4}"
export PERSONA_SFT_GENERATION_AUDIT_HOOK="${PERSONA_SFT_GENERATION_AUDIT_HOOK:-save}"
export PERSONA_SFT_SAVE_EVAL_GENERATIONS="${PERSONA_SFT_SAVE_EVAL_GENERATIONS:-true}"
export PERSONA_SFT_USE_WEIGHTED_SAMPLER="${PERSONA_SFT_USE_WEIGHTED_SAMPLER:-true}"

exec "${SCRIPT_DIR}/run_stage11_persona_sft_v3_quality_6144.sh" "$@"
