#!/usr/bin/env bash
set -euo pipefail

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  echo "Usage: bash scripts/runtime_sh/run_stage11_persona_sft_v3_quality_6144.sh"
  echo "Runs Stage11 persona SFT v3 training. This is a cloud/GPU training job configured by environment variables."
  echo "Set BDA remote path variables and PERSONA_SFT_* options, then run without --help."
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"
source "${SCRIPT_DIR}/../launchers/_path_contract.sh"

PYTHON_BIN="${PYTHON_BIN:-}"
if [[ -z "${PYTHON_BIN}" ]]; then
  if command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN="$(command -v python3)"
  elif command -v python >/dev/null 2>&1; then
    PYTHON_BIN="$(command -v python)"
  elif [[ -x "${BDA_REMOTE_PYTHON_BIN}" ]]; then
    PYTHON_BIN="${BDA_REMOTE_PYTHON_BIN}"
  else
    echo "[ERROR] python executable not found" >&2
    exit 1
  fi
fi

export BDA_PROJECT_ROOT="${REPO_ROOT}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-1}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True,max_split_size_mb:512}"

export INPUT_11_PERSONA_SFT_DATA_ROOT_DIR="${INPUT_11_PERSONA_SFT_DATA_ROOT_DIR:-${BDA_REMOTE_PROJECT_OUTPUT_ROOT}/11_persona_sft_data}"
export OUTPUT_11_PERSONA_SFT_MODELS_ROOT_DIR="${OUTPUT_11_PERSONA_SFT_MODELS_ROOT_DIR:-${BDA_REMOTE_PROJECT_OUTPUT_ROOT}/11_persona_sft_models}"

mkdir -p "${OUTPUT_11_PERSONA_SFT_MODELS_ROOT_DIR}"

export RUN_TAG="${RUN_TAG:-stage11_2_persona_sft_train_v3_quality_6144_fa2_bf16}"
export PERSONA_SFT_BASE_MODEL="${PERSONA_SFT_BASE_MODEL:-${BDA_REMOTE_HF_ROOT}/Qwen3.5-9B}"
export PERSONA_SFT_USE_4BIT="${PERSONA_SFT_USE_4BIT:-false}"
export PERSONA_SFT_USE_BF16="${PERSONA_SFT_USE_BF16:-true}"
export PERSONA_SFT_ATTN_IMPL="${PERSONA_SFT_ATTN_IMPL:-flash_attention_2}"
export PERSONA_SFT_MAX_SEQ_LEN="${PERSONA_SFT_MAX_SEQ_LEN:-6144}"
export PERSONA_SFT_MAX_TRAIN_ROWS="${PERSONA_SFT_MAX_TRAIN_ROWS:-0}"
export PERSONA_SFT_MAX_EVAL_ROWS="${PERSONA_SFT_MAX_EVAL_ROWS:-0}"
export PERSONA_SFT_EPOCHS="${PERSONA_SFT_EPOCHS:-1.0}"
export PERSONA_SFT_LR="${PERSONA_SFT_LR:-5e-5}"
export PERSONA_SFT_WEIGHT_DECAY="${PERSONA_SFT_WEIGHT_DECAY:-0.01}"
export PERSONA_SFT_WARMUP_RATIO="${PERSONA_SFT_WARMUP_RATIO:-0.05}"
export PERSONA_SFT_BATCH_SIZE="${PERSONA_SFT_BATCH_SIZE:-2}"
export PERSONA_SFT_EVAL_BATCH_SIZE="${PERSONA_SFT_EVAL_BATCH_SIZE:-1}"
export PERSONA_SFT_GRAD_ACC="${PERSONA_SFT_GRAD_ACC:-4}"
export PERSONA_SFT_SAVE_STEPS="${PERSONA_SFT_SAVE_STEPS:-50}"
export PERSONA_SFT_EVAL_STEPS="${PERSONA_SFT_EVAL_STEPS:-50}"
export PERSONA_SFT_LOGGING_STEPS="${PERSONA_SFT_LOGGING_STEPS:-5}"
export PERSONA_SFT_SAVE_TOTAL_LIMIT="${PERSONA_SFT_SAVE_TOTAL_LIMIT:-6}"
export PERSONA_SFT_GRADIENT_CHECKPOINTING="${PERSONA_SFT_GRADIENT_CHECKPOINTING:-true}"
export PERSONA_SFT_LORA_R="${PERSONA_SFT_LORA_R:-32}"
export PERSONA_SFT_LORA_ALPHA="${PERSONA_SFT_LORA_ALPHA:-64}"
export PERSONA_SFT_LORA_DROPOUT="${PERSONA_SFT_LORA_DROPOUT:-0.05}"
export PERSONA_SFT_OPTIMIZER="${PERSONA_SFT_OPTIMIZER:-adamw_torch}"
export PERSONA_SFT_GEN_EVAL_ROWS="${PERSONA_SFT_GEN_EVAL_ROWS:-48}"
export PERSONA_SFT_GEN_MAX_NEW_TOKENS="${PERSONA_SFT_GEN_MAX_NEW_TOKENS:-512}"
export PERSONA_SFT_GEN_BATCH_SIZE="${PERSONA_SFT_GEN_BATCH_SIZE:-4}"
export PERSONA_SFT_SAVE_LOG_HISTORY="${PERSONA_SFT_SAVE_LOG_HISTORY:-true}"
export PERSONA_SFT_SAVE_EVAL_GENERATIONS="${PERSONA_SFT_SAVE_EVAL_GENERATIONS:-true}"
export PERSONA_SFT_ALLOW_TF32="${PERSONA_SFT_ALLOW_TF32:-true}"
export PERSONA_SFT_USE_WEIGHTED_SAMPLER="${PERSONA_SFT_USE_WEIGHTED_SAMPLER:-true}"
export PERSONA_SFT_DENSITY_BALANCE_POWER="${PERSONA_SFT_DENSITY_BALANCE_POWER:-0.5}"
export PERSONA_SFT_CUISINE_BALANCE_POWER="${PERSONA_SFT_CUISINE_BALANCE_POWER:-0.35}"
export PERSONA_SFT_CUISINE_BALANCE_MIN_COUNT="${PERSONA_SFT_CUISINE_BALANCE_MIN_COUNT:-16}"
export PERSONA_SFT_SAMPLE_WEIGHT_MAX_MULTIPLIER="${PERSONA_SFT_SAMPLE_WEIGHT_MAX_MULTIPLIER:-4.0}"

echo "[INFO] persona SFT v3 quality-first train"
echo "[INFO] repo=${REPO_ROOT}"
echo "[INFO] python=${PYTHON_BIN}"
echo "[INFO] base_model=${PERSONA_SFT_BASE_MODEL}"
echo "[INFO] input_data_root=${INPUT_11_PERSONA_SFT_DATA_ROOT_DIR}"
echo "[INFO] output_models_root=${OUTPUT_11_PERSONA_SFT_MODELS_ROOT_DIR}"
echo "[INFO] use_4bit=${PERSONA_SFT_USE_4BIT} bf16=${PERSONA_SFT_USE_BF16} attn=${PERSONA_SFT_ATTN_IMPL}"
echo "[INFO] max_seq_len=${PERSONA_SFT_MAX_SEQ_LEN} lr=${PERSONA_SFT_LR} grad_acc=${PERSONA_SFT_GRAD_ACC}"
echo "[INFO] weighted_sampler=${PERSONA_SFT_USE_WEIGHTED_SAMPLER}"
echo "[INFO] density_power=${PERSONA_SFT_DENSITY_BALANCE_POWER} cuisine_power=${PERSONA_SFT_CUISINE_BALANCE_POWER}"

"${PYTHON_BIN}" "${REPO_ROOT}/scripts/11_2_persona_sft_train.py"
