#!/usr/bin/env bash
set -euo pipefail
# Legacy compatibility launcher. Prefer scripts/launchers/stage11_bucket5_train.sh.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
source "${SCRIPT_DIR}/../launchers/_path_contract.sh"
PYTHON_BIN="${PYTHON_BIN:-}"
if [[ -z "${PYTHON_BIN}" ]]; then
  if command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN="$(command -v python3)"
  elif command -v python >/dev/null 2>&1; then
    PYTHON_BIN="$(command -v python)"
  elif [[ -x "${BDA_REMOTE_PYTHON_BIN}" ]]; then
    PYTHON_BIN="${BDA_REMOTE_PYTHON_BIN}"
  else
    echo "[ERROR] python executable not found" >&2
    exit 1
  fi
fi

export PYSPARK_PYTHON="${PYSPARK_PYTHON:-${PYTHON_BIN}}"
export PYSPARK_DRIVER_PYTHON="${PYSPARK_DRIVER_PYTHON:-${PYTHON_BIN}}"

INPUT_11_RUN_DIR="${INPUT_11_RUN_DIR:-}"
INPUT_11_ROOT_DIR="${INPUT_11_ROOT_DIR:-${BDA_REMOTE_FAST_ROOT}/bucket5_top250_semantic_compact_boundary_reason_rm_11_1/output/11_qlora_data}"
OUTPUT_11_MODELS_ROOT_DIR="${OUTPUT_11_MODELS_ROOT_DIR:-${BDA_REMOTE_FAST_ROOT}/bucket5_top250_semantic_compact_boundary_reason_rm_train/output/11_qlora_models}"

mkdir -p "${OUTPUT_11_MODELS_ROOT_DIR}"

export BDA_PROJECT_ROOT="${REPO_ROOT}"
export INPUT_11_RUN_DIR
export INPUT_11_ROOT_DIR
export OUTPUT_11_MODELS_ROOT_DIR
export BUCKETS_OVERRIDE="${BUCKETS_OVERRIDE:-5}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-true}"
export OMP_NUM_THREADS="1"
export MKL_NUM_THREADS="1"
export OPENBLAS_NUM_THREADS="1"
export NUMEXPR_NUM_THREADS="1"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True,max_split_size_mb:128}"

export QLORA_BASE_MODEL="${QLORA_BASE_MODEL:-${BDA_REMOTE_HF_ROOT}/Qwen3.5-9B}"
export QLORA_REQUIRED_BASE_MODEL="${QLORA_REQUIRED_BASE_MODEL:-${QLORA_BASE_MODEL}}"
export QLORA_ENFORCE_REQUIRED_BASE_MODEL="${QLORA_ENFORCE_REQUIRED_BASE_MODEL:-true}"
export QLORA_USE_4BIT="${QLORA_USE_4BIT:-true}"
export QLORA_USE_BF16="${QLORA_USE_BF16:-true}"
export QLORA_QWEN35_SAFE_KBIT_PREP="${QLORA_QWEN35_SAFE_KBIT_PREP:-true}"
export QLORA_QWEN35_FORCE_FLOAT_PARAMS_BF16="${QLORA_QWEN35_FORCE_FLOAT_PARAMS_BF16:-true}"
export QLORA_QWEN35_MAMBA_SSM_DTYPE="${QLORA_QWEN35_MAMBA_SSM_DTYPE:-auto}"
export QLORA_ATTN_IMPLEMENTATION="${QLORA_ATTN_IMPLEMENTATION:-sdpa}"
export QLORA_PAD_TO_MULTIPLE_OF="${QLORA_PAD_TO_MULTIPLE_OF:-32}"

export QLORA_PAIRWISE_SOURCE_MODE="${QLORA_PAIRWISE_SOURCE_MODE:-pool}"
export QLORA_TARGET_TRUE_BANDS="${QLORA_TARGET_TRUE_BANDS:-boundary_11_30}"
if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == "rescue_31_60" ]]; then
  export QLORA_DPO_PAIR_POLICY="${QLORA_DPO_PAIR_POLICY:-v2d}"
else
  export QLORA_DPO_PAIR_POLICY="${QLORA_DPO_PAIR_POLICY:-v1}"
fi
export QLORA_PAIR_PROMPT_STYLE="${QLORA_PAIR_PROMPT_STYLE:-local_listwise_compare}"
if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == "rescue_31_60" ]]; then
  export QLORA_DPO_MAX_PAIRS="${QLORA_DPO_MAX_PAIRS:-16}"
else
  export QLORA_DPO_MAX_PAIRS="${QLORA_DPO_MAX_PAIRS:-12}"
fi
if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == *"rescue_61_100"* ]]; then
  export QLORA_DPO_TRUE_MAX_PAIRS="${QLORA_DPO_TRUE_MAX_PAIRS:-12}"
else
  if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == *"rescue_31_60"* ]]; then
    export QLORA_DPO_TRUE_MAX_PAIRS="${QLORA_DPO_TRUE_MAX_PAIRS:-16}"
  else
    export QLORA_DPO_TRUE_MAX_PAIRS="${QLORA_DPO_TRUE_MAX_PAIRS:-4}"
  fi
fi
export QLORA_DPO_VALID_MAX_PAIRS="${QLORA_DPO_VALID_MAX_PAIRS:-0}"
export QLORA_DPO_HIST_MAX_PAIRS="${QLORA_DPO_HIST_MAX_PAIRS:-0}"
export QLORA_DPO_ALLOW_MID_NEG="${QLORA_DPO_ALLOW_MID_NEG:-true}"
export QLORA_DPO_V2D_TRUE_HEAD_BAND_MAX_PAIRS="${QLORA_DPO_V2D_TRUE_HEAD_BAND_MAX_PAIRS:-4}"
export QLORA_DPO_V2D_TRUE_BOUNDARY_BAND_MAX_PAIRS="${QLORA_DPO_V2D_TRUE_BOUNDARY_BAND_MAX_PAIRS:-6}"
export QLORA_DPO_V2D_TRUE_MID_BAND_MAX_PAIRS="${QLORA_DPO_V2D_TRUE_MID_BAND_MAX_PAIRS:-6}"
if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == "rescue_31_60" ]]; then
  export QLORA_DPO_V2D_TRUE_MID_SLATE_VARIANTS="${QLORA_DPO_V2D_TRUE_MID_SLATE_VARIANTS:-4}"
else
  export QLORA_DPO_V2D_TRUE_MID_SLATE_VARIANTS="${QLORA_DPO_V2D_TRUE_MID_SLATE_VARIANTS:-1}"
fi
export QLORA_DPO_V2D_TRUE_MID_EXPLICIT_SLATE_TYPES="${QLORA_DPO_V2D_TRUE_MID_EXPLICIT_SLATE_TYPES:-$([[ "${QLORA_TARGET_TRUE_BANDS:-}" == "rescue_31_60" ]] && echo true || echo false)}"
export QLORA_DPO_V2D_TRUE_MID_31_40_SLATE_VARIANTS="${QLORA_DPO_V2D_TRUE_MID_31_40_SLATE_VARIANTS:-4}"
export QLORA_DPO_FREEZE_BOUNDARY_11_30_V1="${QLORA_DPO_FREEZE_BOUNDARY_11_30_V1:-true}"
export QLORA_DPO_V2D_MID_GENERIC_FILL="${QLORA_DPO_V2D_MID_GENERIC_FILL:-true}"
if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == *"rescue_61_100"* ]]; then
  export QLORA_DPO_V2D_TRUE_DEEP_BAND_MAX_PAIRS="${QLORA_DPO_V2D_TRUE_DEEP_BAND_MAX_PAIRS:-12}"
  export QLORA_DPO_V2D_TRUE_DEEP_SLATE_VARIANTS="${QLORA_DPO_V2D_TRUE_DEEP_SLATE_VARIANTS:-3}"
  export QLORA_DPO_V2D_TRUE_DEEP_EXPLICIT_SLATE_TYPES="${QLORA_DPO_V2D_TRUE_DEEP_EXPLICIT_SLATE_TYPES:-true}"
  export QLORA_DPO_V2D_TRUE_DEEP_VARIANT_FALLBACK_FILL="${QLORA_DPO_V2D_TRUE_DEEP_VARIANT_FALLBACK_FILL:-true}"
  export QLORA_DPO_V2D_TRUE_DEEP_ALLOW_CROSS_VARIANT_REUSE="${QLORA_DPO_V2D_TRUE_DEEP_ALLOW_CROSS_VARIANT_REUSE:-true}"
  export QLORA_DPO_V2D_TRUE_DEEP_CROSS_VARIANT_REUSE_CAP="${QLORA_DPO_V2D_TRUE_DEEP_CROSS_VARIANT_REUSE_CAP:-2}"
  export QLORA_DPO_V2D_TRUE_DEEP_RELAX_ACTIONABILITY="${QLORA_DPO_V2D_TRUE_DEEP_RELAX_ACTIONABILITY:-true}"
else
  export QLORA_DPO_V2D_TRUE_DEEP_BAND_MAX_PAIRS="${QLORA_DPO_V2D_TRUE_DEEP_BAND_MAX_PAIRS:-3}"
  export QLORA_DPO_V2D_TRUE_DEEP_SLATE_VARIANTS="${QLORA_DPO_V2D_TRUE_DEEP_SLATE_VARIANTS:-1}"
  export QLORA_DPO_V2D_TRUE_DEEP_EXPLICIT_SLATE_TYPES="${QLORA_DPO_V2D_TRUE_DEEP_EXPLICIT_SLATE_TYPES:-false}"
  export QLORA_DPO_V2D_TRUE_DEEP_VARIANT_FALLBACK_FILL="${QLORA_DPO_V2D_TRUE_DEEP_VARIANT_FALLBACK_FILL:-false}"
  export QLORA_DPO_V2D_TRUE_DEEP_ALLOW_CROSS_VARIANT_REUSE="${QLORA_DPO_V2D_TRUE_DEEP_ALLOW_CROSS_VARIANT_REUSE:-false}"
  export QLORA_DPO_V2D_TRUE_DEEP_CROSS_VARIANT_REUSE_CAP="${QLORA_DPO_V2D_TRUE_DEEP_CROSS_VARIANT_REUSE_CAP:-1}"
  export QLORA_DPO_V2D_TRUE_DEEP_RELAX_ACTIONABILITY="${QLORA_DPO_V2D_TRUE_DEEP_RELAX_ACTIONABILITY:-false}"
fi
export QLORA_DPO_V2D_TRUE_DEEP_RELAX_MIN_SIGNAL_COUNT="${QLORA_DPO_V2D_TRUE_DEEP_RELAX_MIN_SIGNAL_COUNT:-3}"
export QLORA_DPO_V2D_TRUE_HEAD_MIN_PACK="${QLORA_DPO_V2D_TRUE_HEAD_MIN_PACK:-2}"
export QLORA_DPO_V2D_TRUE_BOUNDARY_MIN_PACK="${QLORA_DPO_V2D_TRUE_BOUNDARY_MIN_PACK:-4}"
export QLORA_DPO_V2D_TRUE_MID_MIN_PACK="${QLORA_DPO_V2D_TRUE_MID_MIN_PACK:-3}"
export QLORA_DPO_V2D_TRUE_DEEP_MIN_PACK="${QLORA_DPO_V2D_TRUE_DEEP_MIN_PACK:-2}"
export QLORA_DPO_LOCAL_LISTWISE_MAX_RIVALS="${QLORA_DPO_LOCAL_LISTWISE_MAX_RIVALS:-4}"
export QLORA_DPO_V2D_TRUE_MID_SAME_BAND_QUOTA="${QLORA_DPO_V2D_TRUE_MID_SAME_BAND_QUOTA:-6}"
if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == *"rescue_61_100"* ]]; then
  export QLORA_DPO_V2D_TRUE_DEEP_SAME_BAND_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_SAME_BAND_QUOTA:-3}"
  export QLORA_DPO_V2D_TRUE_DEEP_MID_BAND_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_MID_BAND_QUOTA:-4}"
  export QLORA_DPO_V2D_TRUE_DEEP_BOUNDARY_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_BOUNDARY_QUOTA:-3}"
  export QLORA_DPO_V2D_TRUE_DEEP_HEAD_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_HEAD_QUOTA:-2}"
else
  export QLORA_DPO_V2D_TRUE_DEEP_SAME_BAND_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_SAME_BAND_QUOTA:-2}"
  export QLORA_DPO_V2D_TRUE_DEEP_MID_BAND_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_MID_BAND_QUOTA:-1}"
  export QLORA_DPO_V2D_TRUE_DEEP_BOUNDARY_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_BOUNDARY_QUOTA:-1}"
  export QLORA_DPO_V2D_TRUE_DEEP_HEAD_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_HEAD_QUOTA:-0}"
fi
export QLORA_DPO_V2D_TRUE_HEAD_PRESERVE_QUOTA="${QLORA_DPO_V2D_TRUE_HEAD_PRESERVE_QUOTA:-2}"
export QLORA_DPO_V2D_TRUE_BOUNDARY_RESCUE_QUOTA="${QLORA_DPO_V2D_TRUE_BOUNDARY_RESCUE_QUOTA:-4}"
export QLORA_DPO_V2D_TRUE_MULTI_ROUTE_RESCUE_QUOTA="${QLORA_DPO_V2D_TRUE_MULTI_ROUTE_RESCUE_QUOTA:-2}"
export QLORA_DPO_V2D_TRUE_TOPK_QUOTA="${QLORA_DPO_V2D_TRUE_TOPK_QUOTA:-2}"
export QLORA_DPO_V2D_TRUE_FIT_RISK_QUOTA="${QLORA_DPO_V2D_TRUE_FIT_RISK_QUOTA:-1}"
export QLORA_DPO_V2D_TRUE_COMPETITION_QUOTA="${QLORA_DPO_V2D_TRUE_COMPETITION_QUOTA:-1}"
export QLORA_DPO_V2D_TRUE_SEMANTIC_QUOTA="${QLORA_DPO_V2D_TRUE_SEMANTIC_QUOTA:-0}"
export QLORA_DPO_V2D_TRUE_DEEP_SEMANTIC_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_SEMANTIC_QUOTA:-0}"
export QLORA_DPO_V2D_TRUE_REASON_PRIMARY_QUOTA="${QLORA_DPO_V2D_TRUE_REASON_PRIMARY_QUOTA:-1}"
export QLORA_DPO_V2D_TRUE_REASON_AUX_QUOTA="${QLORA_DPO_V2D_TRUE_REASON_AUX_QUOTA:-1}"
export QLORA_DPO_V2D_TRUE_HEAD_FALLBACK_QUOTA="${QLORA_DPO_V2D_TRUE_HEAD_FALLBACK_QUOTA:-1}"
export QLORA_DPO_V2D_TRUE_BOUNDARY_FALLBACK_QUOTA="${QLORA_DPO_V2D_TRUE_BOUNDARY_FALLBACK_QUOTA:-1}"
export QLORA_DPO_V2D_TRUE_MID_FALLBACK_QUOTA="${QLORA_DPO_V2D_TRUE_MID_FALLBACK_QUOTA:-1}"
export QLORA_DPO_V2D_TRUE_DEEP_FALLBACK_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_FALLBACK_QUOTA:-1}"
export QLORA_DPO_V2D_VALID_BOUNDARY_RESCUE_QUOTA="${QLORA_DPO_V2D_VALID_BOUNDARY_RESCUE_QUOTA:-0}"
export QLORA_DPO_V2D_VALID_COMPETITION_QUOTA="${QLORA_DPO_V2D_VALID_COMPETITION_QUOTA:-0}"
export QLORA_DPO_V2D_VALID_FIT_RISK_QUOTA="${QLORA_DPO_V2D_VALID_FIT_RISK_QUOTA:-0}"
export QLORA_DPO_V2D_VALID_SEMANTIC_QUOTA="${QLORA_DPO_V2D_VALID_SEMANTIC_QUOTA:-0}"
export QLORA_DPO_MULTI_ROUTE_PRESERVE_SOURCE_EDGE_MIN="${QLORA_DPO_MULTI_ROUTE_PRESERVE_SOURCE_EDGE_MIN:-2}"
export QLORA_DPO_RESCUE_31_60_PRIMARY_BLOCKER_MIN_RANK="${QLORA_DPO_RESCUE_31_60_PRIMARY_BLOCKER_MIN_RANK:-21}"
export QLORA_DPO_RESCUE_31_60_PRIMARY_BLOCKER_MAX_RANK="${QLORA_DPO_RESCUE_31_60_PRIMARY_BLOCKER_MAX_RANK:-30}"
export QLORA_DPO_RESCUE_31_60_SECONDARY_BLOCKER_MIN_RANK="${QLORA_DPO_RESCUE_31_60_SECONDARY_BLOCKER_MIN_RANK:-7}"
export QLORA_DPO_RESCUE_31_60_SECONDARY_BLOCKER_MAX_RANK="${QLORA_DPO_RESCUE_31_60_SECONDARY_BLOCKER_MAX_RANK:-20}"
export QLORA_DPO_RESCUE_31_60_NEG_RANK_MAX="${QLORA_DPO_RESCUE_31_60_NEG_RANK_MAX:-30}"
export QLORA_DPO_RESCUE_61_100_NEG_RANK_MAX="${QLORA_DPO_RESCUE_61_100_NEG_RANK_MAX:-50}"

export QLORA_RM_REQUIRE_SCORING_PROMPT="${QLORA_RM_REQUIRE_SCORING_PROMPT:-true}"
export QLORA_RM_EXPECTED_PROMPT_MODE="${QLORA_RM_EXPECTED_PROMPT_MODE:-semantic_compact_boundary_rm}"
export QLORA_RM_OBJECTIVE="${QLORA_RM_OBJECTIVE:-listwise}"
export QLORA_RM_TRUE_PAIR_WEIGHT="${QLORA_RM_TRUE_PAIR_WEIGHT:-1.0}"
export QLORA_RM_VALID_PAIR_WEIGHT="${QLORA_RM_VALID_PAIR_WEIGHT:-0.35}"
export QLORA_RM_HIST_PAIR_WEIGHT="${QLORA_RM_HIST_PAIR_WEIGHT:-0.0}"
export QLORA_RM_BOUNDARY_PAIR_WEIGHT="${QLORA_RM_BOUNDARY_PAIR_WEIGHT:-1.35}"
export QLORA_RM_STRUCTURED_PAIR_WEIGHT="${QLORA_RM_STRUCTURED_PAIR_WEIGHT:-1.2}"
export QLORA_RM_SLOT_DECAY="${QLORA_RM_SLOT_DECAY:-0.85}"
export QLORA_RM_SAMPLE_WEIGHT_MODE="${QLORA_RM_SAMPLE_WEIGHT_MODE:-capped_max}"
export QLORA_RM_SAMPLE_WEIGHT_CAP="${QLORA_RM_SAMPLE_WEIGHT_CAP:-1.25}"
export QLORA_RM_LISTWISE_MAX_NEGATIVES="${QLORA_RM_LISTWISE_MAX_NEGATIVES:-6}"
export QLORA_RM_LISTWISE_MIN_NEGATIVES="${QLORA_RM_LISTWISE_MIN_NEGATIVES:-3}"
export QLORA_RM_LISTWISE_TRAIN_MIN_NEGATIVES="${QLORA_RM_LISTWISE_TRAIN_MIN_NEGATIVES:-2}"
export QLORA_RM_LISTWISE_EVAL_MIN_NEGATIVES="${QLORA_RM_LISTWISE_EVAL_MIN_NEGATIVES:-2}"
if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == "rescue_31_60" ]]; then
  export QLORA_RM_EVAL_MAX_PAIRS="${QLORA_RM_EVAL_MAX_PAIRS:-16}"
else
  export QLORA_RM_EVAL_MAX_PAIRS="${QLORA_RM_EVAL_MAX_PAIRS:-12}"
fi
if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == *"rescue_61_100"* ]]; then
  export QLORA_RM_EVAL_TRUE_MAX_PAIRS="${QLORA_RM_EVAL_TRUE_MAX_PAIRS:-12}"
else
  if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == *"rescue_31_60"* ]]; then
    export QLORA_RM_EVAL_TRUE_MAX_PAIRS="${QLORA_RM_EVAL_TRUE_MAX_PAIRS:-16}"
  else
    export QLORA_RM_EVAL_TRUE_MAX_PAIRS="${QLORA_RM_EVAL_TRUE_MAX_PAIRS:-4}"
  fi
fi
export QLORA_RM_EVAL_VALID_MAX_PAIRS="${QLORA_RM_EVAL_VALID_MAX_PAIRS:-0}"
export QLORA_RM_EVAL_HIST_MAX_PAIRS="${QLORA_RM_EVAL_HIST_MAX_PAIRS:-0}"
export QLORA_RM_LISTWISE_TEMPERATURE="${QLORA_RM_LISTWISE_TEMPERATURE:-1.0}"
export QLORA_RM_SCORE_CHUNK_SIZE="${QLORA_RM_SCORE_CHUNK_SIZE:-2}"
export QLORA_BOUNDARY_PROBE_SCORE_MODE="${QLORA_BOUNDARY_PROBE_SCORE_MODE:-boundary_head_reason_weighted}"
export QLORA_BOUNDARY_PROBE_HEAD_WEIGHT="${QLORA_BOUNDARY_PROBE_HEAD_WEIGHT:-0.30}"
export QLORA_BOUNDARY_PROBE_REASON_WEIGHT="${QLORA_BOUNDARY_PROBE_REASON_WEIGHT:-0.15}"
export QLORA_BOUNDARY_PROBE_REASON_TARGETS="${QLORA_BOUNDARY_PROBE_REASON_TARGETS:-semantic_edge_xgb_ambiguous,semantic_edge_underweighted,channel_context_underweighted,multi_route_underweighted}"
if [[ -z "${QLORA_BEST_MODEL_METRIC:-}" ]]; then
  if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == "rescue_31_60" ]]; then
    export QLORA_BEST_MODEL_METRIC="eval_rescue_31_40_true_win_rate"
  elif [[ "${QLORA_TARGET_TRUE_BANDS:-}" == "rescue_61_100" ]]; then
    export QLORA_BEST_MODEL_METRIC="eval_rescue_61_100_true_win_rate"
  else
    export QLORA_BEST_MODEL_METRIC="eval_boundary_probe_score"
  fi
else
  export QLORA_BEST_MODEL_METRIC="${QLORA_BEST_MODEL_METRIC}"
fi

if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == "rescue_31_60" ]]; then
  export QLORA_MAX_SEQ_LEN="${QLORA_MAX_SEQ_LEN:-1280}"
  export QLORA_BATCH_SIZE="${QLORA_BATCH_SIZE:-2}"
  export QLORA_EVAL_BATCH_SIZE="${QLORA_EVAL_BATCH_SIZE:-2}"
  export QLORA_GRAD_ACC="${QLORA_GRAD_ACC:-4}"
  export QLORA_RM_SCORE_CHUNK_SIZE="${QLORA_RM_SCORE_CHUNK_SIZE:-4}"
else
  export QLORA_MAX_SEQ_LEN="${QLORA_MAX_SEQ_LEN:-1184}"
  export QLORA_BATCH_SIZE="${QLORA_BATCH_SIZE:-1}"
  export QLORA_EVAL_BATCH_SIZE="${QLORA_EVAL_BATCH_SIZE:-1}"
  export QLORA_GRAD_ACC="${QLORA_GRAD_ACC:-8}"
fi
export QLORA_EPOCHS="${QLORA_EPOCHS:-1.3}"
export QLORA_LR="${QLORA_LR:-4e-5}"
export QLORA_WARMUP_RATIO="${QLORA_WARMUP_RATIO:-0.08}"
export QLORA_EVAL_STEPS="${QLORA_EVAL_STEPS:-50}"
export QLORA_SAVE_STEPS="${QLORA_SAVE_STEPS:-50}"
export QLORA_SAVE_TOTAL_LIMIT="${QLORA_SAVE_TOTAL_LIMIT:-4}"
export QLORA_LOGGING_STEPS="${QLORA_LOGGING_STEPS:-5}"
export QLORA_GRADIENT_CHECKPOINTING="${QLORA_GRADIENT_CHECKPOINTING:-true}"
export QLORA_SAVE_EVAL_SCORE_DUMPS="${QLORA_SAVE_EVAL_SCORE_DUMPS:-true}"
export QLORA_EVAL_SCORE_DUMPS_DIRNAME="${QLORA_EVAL_SCORE_DUMPS_DIRNAME:-eval_score_dumps}"

echo "[INFO] bucket5 stage11 top250 semantic_compact_boundary_rm trainer"
echo "[INFO] repo=${REPO_ROOT}"
echo "[INFO] input_11=${INPUT_11_RUN_DIR:-<latest under root>}"
echo "[INFO] input_11_root=${INPUT_11_ROOT_DIR}"
echo "[INFO] output_11_models=${OUTPUT_11_MODELS_ROOT_DIR}"
echo "[INFO] python=${PYTHON_BIN}"
echo "[INFO] base_model=${QLORA_BASE_MODEL}"
echo "[INFO] target_true_bands=${QLORA_TARGET_TRUE_BANDS}"
echo "[INFO] pair_policy=${QLORA_DPO_PAIR_POLICY}"
echo "[INFO] pair_prompt_style=${QLORA_PAIR_PROMPT_STYLE}"
echo "[INFO] dpo_true_max_pairs=${QLORA_DPO_TRUE_MAX_PAIRS} rm_eval_true_max_pairs=${QLORA_RM_EVAL_TRUE_MAX_PAIRS}"
echo "[INFO] v2d_mid_same_band_quota.true=${QLORA_DPO_V2D_TRUE_MID_SAME_BAND_QUOTA}"
echo "[INFO] v2d_mid_slate_variants.true=${QLORA_DPO_V2D_TRUE_MID_SLATE_VARIANTS}"
echo "[INFO] freeze_boundary_11_30_v1=${QLORA_DPO_FREEZE_BOUNDARY_11_30_V1}"
echo "[INFO] v2d_mid_generic_fill=${QLORA_DPO_V2D_MID_GENERIC_FILL}"
echo "[INFO] v2d_deep_same_band_quota.true=${QLORA_DPO_V2D_TRUE_DEEP_SAME_BAND_QUOTA}"
echo "[INFO] v2d_deep_mid_band_quota.true=${QLORA_DPO_V2D_TRUE_DEEP_MID_BAND_QUOTA}"
echo "[INFO] v2d_deep_boundary_quota.true=${QLORA_DPO_V2D_TRUE_DEEP_BOUNDARY_QUOTA}"
echo "[INFO] v2d_deep_head_quota.true=${QLORA_DPO_V2D_TRUE_DEEP_HEAD_QUOTA}"
echo "[INFO] v2d_deep_slate_variants.true=${QLORA_DPO_V2D_TRUE_DEEP_SLATE_VARIANTS}"
echo "[INFO] v2d_deep_explicit_slate_types=${QLORA_DPO_V2D_TRUE_DEEP_EXPLICIT_SLATE_TYPES}"
echo "[INFO] v2d_deep_variant_fallback_fill=${QLORA_DPO_V2D_TRUE_DEEP_VARIANT_FALLBACK_FILL}"
echo "[INFO] v2d_deep_allow_cross_variant_reuse=${QLORA_DPO_V2D_TRUE_DEEP_ALLOW_CROSS_VARIANT_REUSE} cap=${QLORA_DPO_V2D_TRUE_DEEP_CROSS_VARIANT_REUSE_CAP}"
echo "[INFO] v2d_deep_relax_actionability=${QLORA_DPO_V2D_TRUE_DEEP_RELAX_ACTIONABILITY} min_signal=${QLORA_DPO_V2D_TRUE_DEEP_RELAX_MIN_SIGNAL_COUNT}"
echo "[INFO] v2d_head_guard_quota.true=${QLORA_DPO_V2D_TRUE_HEAD_PRESERVE_QUOTA}"
echo "[INFO] v2d_boundary_rescue_quota.true=${QLORA_DPO_V2D_TRUE_BOUNDARY_RESCUE_QUOTA}"
echo "[INFO] v2d_multi_route_rescue_quota.true=${QLORA_DPO_V2D_TRUE_MULTI_ROUTE_RESCUE_QUOTA}"
echo "[INFO] rescue_31_60_blockers.primary=${QLORA_DPO_RESCUE_31_60_PRIMARY_BLOCKER_MIN_RANK}-${QLORA_DPO_RESCUE_31_60_PRIMARY_BLOCKER_MAX_RANK} secondary=${QLORA_DPO_RESCUE_31_60_SECONDARY_BLOCKER_MIN_RANK}-${QLORA_DPO_RESCUE_31_60_SECONDARY_BLOCKER_MAX_RANK}"
echo "[INFO] v2d_reason_primary_quota.true=${QLORA_DPO_V2D_TRUE_REASON_PRIMARY_QUOTA}"
echo "[INFO] v2d_reason_aux_quota.true=${QLORA_DPO_V2D_TRUE_REASON_AUX_QUOTA}"
echo "[INFO] v2d_valid_boundary_rescue_quota=${QLORA_DPO_V2D_VALID_BOUNDARY_RESCUE_QUOTA}"
echo "[INFO] rm_objective=${QLORA_RM_OBJECTIVE}"
echo "[INFO] rm_slot_decay=${QLORA_RM_SLOT_DECAY}"
echo "[INFO] rm_sample_weight_mode=${QLORA_RM_SAMPLE_WEIGHT_MODE}"
echo "[INFO] rm_score_chunk_size=${QLORA_RM_SCORE_CHUNK_SIZE}"
echo "[INFO] boundary_probe_score_mode=${QLORA_BOUNDARY_PROBE_SCORE_MODE}"
echo "[INFO] best_model_metric=${QLORA_BEST_MODEL_METRIC}"
echo "[INFO] save_eval_score_dumps=${QLORA_SAVE_EVAL_SCORE_DUMPS} dump_dirname=${QLORA_EVAL_SCORE_DUMPS_DIRNAME}"
echo "[INFO] current_cloud_fastpath train.pad_to_multiple_of=${QLORA_PAD_TO_MULTIPLE_OF} train.attn_implementation=${QLORA_ATTN_IMPLEMENTATION:-<default>}"
echo "[INFO] thread_env omp=${OMP_NUM_THREADS} mkl=${MKL_NUM_THREADS} openblas=${OPENBLAS_NUM_THREADS} numexpr=${NUMEXPR_NUM_THREADS}"

"${PYTHON_BIN}" "${REPO_ROOT}/scripts/11_2_rm_train.py"
