#!/usr/bin/env bash
set -euo pipefail
# Legacy compatibility launcher. Prefer scripts/launchers/stage11_bucket5_export_only.sh.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
source "${SCRIPT_DIR}/../launchers/_path_contract.sh"
PYTHON_BIN="${PYTHON_BIN:-}"
if [[ -z "${PYTHON_BIN}" ]]; then
  if command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN="$(command -v python3)"
  elif command -v python >/dev/null 2>&1; then
    PYTHON_BIN="$(command -v python)"
  elif [[ -x "${BDA_REMOTE_PYTHON_BIN}" ]]; then
    PYTHON_BIN="${BDA_REMOTE_PYTHON_BIN}"
  else
    echo "[ERROR] python executable not found" >&2
    exit 1
  fi
fi

export PYSPARK_PYTHON="${PYSPARK_PYTHON:-${PYTHON_BIN}}"
export PYSPARK_DRIVER_PYTHON="${PYSPARK_DRIVER_PYTHON:-${PYTHON_BIN}}"

INPUT_11_RUN_DIR="${INPUT_11_RUN_DIR:-}"
if [[ -z "${INPUT_11_RUN_DIR}" ]]; then
  echo "[ERROR] INPUT_11_RUN_DIR is required" >&2
  exit 1
fi

INPUT_09_RUN_DIR="${INPUT_09_RUN_DIR:-${BDA_REMOTE_PROJECT_OUTPUT_ROOT}/09_candidate_fusion_structural_v5_sourceparity/20260324_030511_full_stage09_candidate_fusion}"
OUTPUT_11_PAIRWISE_ROOT_DIR="${OUTPUT_11_PAIRWISE_ROOT_DIR:-${BDA_REMOTE_FAST_ROOT}/bucket5_top250_semantic_compact_boundary_reason_rm_export_only/output/11_qlora_pairwise}"
SPARK_LOCAL_DIR_DEFAULT="${REPO_ROOT}/data/spark-tmp"

mkdir -p "${OUTPUT_11_PAIRWISE_ROOT_DIR}" "${SPARK_LOCAL_DIR_DEFAULT}"

export BDA_PROJECT_ROOT="${REPO_ROOT}"
export INPUT_11_RUN_DIR
export INPUT_09_RUN_DIR
export OUTPUT_11_PAIRWISE_ROOT_DIR
export BUCKETS_OVERRIDE="${BUCKETS_OVERRIDE:-5}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-true}"
export OMP_NUM_THREADS="1"
export MKL_NUM_THREADS="1"
export OPENBLAS_NUM_THREADS="1"
export NUMEXPR_NUM_THREADS="1"

export SPARK_MASTER="${SPARK_MASTER:-local[24]}"
export SPARK_DRIVER_MEMORY="${SPARK_DRIVER_MEMORY:-76g}"
export SPARK_EXECUTOR_MEMORY="${SPARK_EXECUTOR_MEMORY:-76g}"
export SPARK_LOCAL_DIR="${SPARK_LOCAL_DIR:-${SPARK_LOCAL_DIR_DEFAULT}}"
export SPARK_SQL_SHUFFLE_PARTITIONS="${SPARK_SQL_SHUFFLE_PARTITIONS:-192}"
export SPARK_DEFAULT_PARALLELISM="${SPARK_DEFAULT_PARALLELISM:-192}"
export SPARK_SQL_CONSTRAINT_PROPAGATION_ENABLED="${SPARK_SQL_CONSTRAINT_PROPAGATION_ENABLED:-false}"
export SPARK_NETWORK_TIMEOUT="${SPARK_NETWORK_TIMEOUT:-1200s}"
export SPARK_EXECUTOR_HEARTBEAT_INTERVAL="${SPARK_EXECUTOR_HEARTBEAT_INTERVAL:-120s}"
export SPARK_DRIVER_HOST="${SPARK_DRIVER_HOST:-127.0.0.1}"
export SPARK_DRIVER_BIND_ADDRESS="${SPARK_DRIVER_BIND_ADDRESS:-127.0.0.1}"
export SPARK_TMP_SESSION_ISOLATION="${SPARK_TMP_SESSION_ISOLATION:-true}"
export SPARK_TMP_AUTOCLEAN_ENABLED="${SPARK_TMP_AUTOCLEAN_ENABLED:-false}"
export SPARK_TMP_CLEAN_ON_EXIT="${SPARK_TMP_CLEAN_ON_EXIT:-true}"
export SPARK_TMP_RETENTION_HOURS="${SPARK_TMP_RETENTION_HOURS:-8}"
export SPARK_TMP_CLEAN_MAX_ENTRIES="${SPARK_TMP_CLEAN_MAX_ENTRIES:-3000}"

export QLORA_ENFORCE_STAGE09_GATE="${QLORA_ENFORCE_STAGE09_GATE:-false}"
export QLORA_PROMPT_MODE="${QLORA_PROMPT_MODE:-semantic_compact_boundary_rm}"
export QLORA_PAIRWISE_SOURCE_MODE="${QLORA_PAIRWISE_SOURCE_MODE:-pool}"
export QLORA_TARGET_TRUE_BANDS="${QLORA_TARGET_TRUE_BANDS:-boundary_11_30}"
if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == "rescue_31_60" ]]; then
  export QLORA_DPO_PAIR_POLICY="${QLORA_DPO_PAIR_POLICY:-v2d}"
else
  export QLORA_DPO_PAIR_POLICY="${QLORA_DPO_PAIR_POLICY:-v1}"
fi
export QLORA_PAIR_PROMPT_STYLE="${QLORA_PAIR_PROMPT_STYLE:-local_listwise_compare}"
if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == "rescue_31_60" ]]; then
  export QLORA_DPO_MAX_PAIRS="${QLORA_DPO_MAX_PAIRS:-16}"
else
  export QLORA_DPO_MAX_PAIRS="${QLORA_DPO_MAX_PAIRS:-12}"
fi
if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == *"rescue_61_100"* ]]; then
  export QLORA_DPO_TRUE_MAX_PAIRS="${QLORA_DPO_TRUE_MAX_PAIRS:-12}"
else
  if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == *"rescue_31_60"* ]]; then
    export QLORA_DPO_TRUE_MAX_PAIRS="${QLORA_DPO_TRUE_MAX_PAIRS:-16}"
  else
    export QLORA_DPO_TRUE_MAX_PAIRS="${QLORA_DPO_TRUE_MAX_PAIRS:-4}"
  fi
fi
export QLORA_DPO_VALID_MAX_PAIRS="${QLORA_DPO_VALID_MAX_PAIRS:-0}"
export QLORA_DPO_HIST_MAX_PAIRS="${QLORA_DPO_HIST_MAX_PAIRS:-0}"
export QLORA_DPO_ALLOW_MID_NEG="${QLORA_DPO_ALLOW_MID_NEG:-true}"
export QLORA_DPO_V2D_TRUE_HEAD_BAND_MAX_PAIRS="${QLORA_DPO_V2D_TRUE_HEAD_BAND_MAX_PAIRS:-4}"
export QLORA_DPO_V2D_TRUE_BOUNDARY_BAND_MAX_PAIRS="${QLORA_DPO_V2D_TRUE_BOUNDARY_BAND_MAX_PAIRS:-6}"
export QLORA_DPO_V2D_TRUE_MID_BAND_MAX_PAIRS="${QLORA_DPO_V2D_TRUE_MID_BAND_MAX_PAIRS:-6}"
if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == "rescue_31_60" ]]; then
  export QLORA_DPO_V2D_TRUE_MID_SLATE_VARIANTS="${QLORA_DPO_V2D_TRUE_MID_SLATE_VARIANTS:-4}"
else
  export QLORA_DPO_V2D_TRUE_MID_SLATE_VARIANTS="${QLORA_DPO_V2D_TRUE_MID_SLATE_VARIANTS:-1}"
fi
export QLORA_DPO_V2D_TRUE_MID_EXPLICIT_SLATE_TYPES="${QLORA_DPO_V2D_TRUE_MID_EXPLICIT_SLATE_TYPES:-$([[ "${QLORA_TARGET_TRUE_BANDS:-}" == "rescue_31_60" ]] && echo true || echo false)}"
export QLORA_DPO_V2D_TRUE_MID_31_40_SLATE_VARIANTS="${QLORA_DPO_V2D_TRUE_MID_31_40_SLATE_VARIANTS:-4}"
export QLORA_DPO_FREEZE_BOUNDARY_11_30_V1="${QLORA_DPO_FREEZE_BOUNDARY_11_30_V1:-true}"
export QLORA_DPO_V2D_MID_GENERIC_FILL="${QLORA_DPO_V2D_MID_GENERIC_FILL:-true}"
if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == *"rescue_61_100"* ]]; then
  export QLORA_DPO_V2D_TRUE_DEEP_BAND_MAX_PAIRS="${QLORA_DPO_V2D_TRUE_DEEP_BAND_MAX_PAIRS:-12}"
  export QLORA_DPO_V2D_TRUE_DEEP_SLATE_VARIANTS="${QLORA_DPO_V2D_TRUE_DEEP_SLATE_VARIANTS:-3}"
  export QLORA_DPO_V2D_TRUE_DEEP_EXPLICIT_SLATE_TYPES="${QLORA_DPO_V2D_TRUE_DEEP_EXPLICIT_SLATE_TYPES:-true}"
  export QLORA_DPO_V2D_TRUE_DEEP_VARIANT_FALLBACK_FILL="${QLORA_DPO_V2D_TRUE_DEEP_VARIANT_FALLBACK_FILL:-true}"
  export QLORA_DPO_V2D_TRUE_DEEP_ALLOW_CROSS_VARIANT_REUSE="${QLORA_DPO_V2D_TRUE_DEEP_ALLOW_CROSS_VARIANT_REUSE:-true}"
  export QLORA_DPO_V2D_TRUE_DEEP_CROSS_VARIANT_REUSE_CAP="${QLORA_DPO_V2D_TRUE_DEEP_CROSS_VARIANT_REUSE_CAP:-2}"
  export QLORA_DPO_V2D_TRUE_DEEP_RELAX_ACTIONABILITY="${QLORA_DPO_V2D_TRUE_DEEP_RELAX_ACTIONABILITY:-true}"
else
  export QLORA_DPO_V2D_TRUE_DEEP_BAND_MAX_PAIRS="${QLORA_DPO_V2D_TRUE_DEEP_BAND_MAX_PAIRS:-3}"
  export QLORA_DPO_V2D_TRUE_DEEP_SLATE_VARIANTS="${QLORA_DPO_V2D_TRUE_DEEP_SLATE_VARIANTS:-1}"
  export QLORA_DPO_V2D_TRUE_DEEP_EXPLICIT_SLATE_TYPES="${QLORA_DPO_V2D_TRUE_DEEP_EXPLICIT_SLATE_TYPES:-false}"
  export QLORA_DPO_V2D_TRUE_DEEP_VARIANT_FALLBACK_FILL="${QLORA_DPO_V2D_TRUE_DEEP_VARIANT_FALLBACK_FILL:-false}"
  export QLORA_DPO_V2D_TRUE_DEEP_ALLOW_CROSS_VARIANT_REUSE="${QLORA_DPO_V2D_TRUE_DEEP_ALLOW_CROSS_VARIANT_REUSE:-false}"
  export QLORA_DPO_V2D_TRUE_DEEP_CROSS_VARIANT_REUSE_CAP="${QLORA_DPO_V2D_TRUE_DEEP_CROSS_VARIANT_REUSE_CAP:-1}"
  export QLORA_DPO_V2D_TRUE_DEEP_RELAX_ACTIONABILITY="${QLORA_DPO_V2D_TRUE_DEEP_RELAX_ACTIONABILITY:-false}"
fi
export QLORA_DPO_V2D_TRUE_DEEP_RELAX_MIN_SIGNAL_COUNT="${QLORA_DPO_V2D_TRUE_DEEP_RELAX_MIN_SIGNAL_COUNT:-3}"
export QLORA_DPO_V2D_TRUE_HEAD_MIN_PACK="${QLORA_DPO_V2D_TRUE_HEAD_MIN_PACK:-2}"
export QLORA_DPO_V2D_TRUE_BOUNDARY_MIN_PACK="${QLORA_DPO_V2D_TRUE_BOUNDARY_MIN_PACK:-4}"
export QLORA_DPO_V2D_TRUE_MID_MIN_PACK="${QLORA_DPO_V2D_TRUE_MID_MIN_PACK:-3}"
export QLORA_DPO_V2D_TRUE_DEEP_MIN_PACK="${QLORA_DPO_V2D_TRUE_DEEP_MIN_PACK:-2}"
export QLORA_DPO_LOCAL_LISTWISE_MAX_RIVALS="${QLORA_DPO_LOCAL_LISTWISE_MAX_RIVALS:-4}"
export QLORA_DPO_V2D_TRUE_MID_SAME_BAND_QUOTA="${QLORA_DPO_V2D_TRUE_MID_SAME_BAND_QUOTA:-6}"
if [[ "${QLORA_TARGET_TRUE_BANDS:-}" == *"rescue_61_100"* ]]; then
  export QLORA_DPO_V2D_TRUE_DEEP_SAME_BAND_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_SAME_BAND_QUOTA:-3}"
  export QLORA_DPO_V2D_TRUE_DEEP_MID_BAND_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_MID_BAND_QUOTA:-4}"
  export QLORA_DPO_V2D_TRUE_DEEP_BOUNDARY_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_BOUNDARY_QUOTA:-3}"
  export QLORA_DPO_V2D_TRUE_DEEP_HEAD_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_HEAD_QUOTA:-2}"
else
  export QLORA_DPO_V2D_TRUE_DEEP_SAME_BAND_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_SAME_BAND_QUOTA:-2}"
  export QLORA_DPO_V2D_TRUE_DEEP_MID_BAND_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_MID_BAND_QUOTA:-1}"
  export QLORA_DPO_V2D_TRUE_DEEP_BOUNDARY_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_BOUNDARY_QUOTA:-1}"
  export QLORA_DPO_V2D_TRUE_DEEP_HEAD_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_HEAD_QUOTA:-0}"
fi
export QLORA_DPO_V2D_TRUE_HEAD_PRESERVE_QUOTA="${QLORA_DPO_V2D_TRUE_HEAD_PRESERVE_QUOTA:-2}"
export QLORA_DPO_V2D_TRUE_BOUNDARY_RESCUE_QUOTA="${QLORA_DPO_V2D_TRUE_BOUNDARY_RESCUE_QUOTA:-4}"
export QLORA_DPO_V2D_TRUE_MULTI_ROUTE_RESCUE_QUOTA="${QLORA_DPO_V2D_TRUE_MULTI_ROUTE_RESCUE_QUOTA:-2}"
export QLORA_DPO_V2D_TRUE_TOPK_QUOTA="${QLORA_DPO_V2D_TRUE_TOPK_QUOTA:-2}"
export QLORA_DPO_V2D_TRUE_FIT_RISK_QUOTA="${QLORA_DPO_V2D_TRUE_FIT_RISK_QUOTA:-1}"
export QLORA_DPO_V2D_TRUE_COMPETITION_QUOTA="${QLORA_DPO_V2D_TRUE_COMPETITION_QUOTA:-1}"
export QLORA_DPO_V2D_TRUE_SEMANTIC_QUOTA="${QLORA_DPO_V2D_TRUE_SEMANTIC_QUOTA:-0}"
export QLORA_DPO_V2D_TRUE_DEEP_SEMANTIC_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_SEMANTIC_QUOTA:-0}"
export QLORA_DPO_V2D_TRUE_REASON_PRIMARY_QUOTA="${QLORA_DPO_V2D_TRUE_REASON_PRIMARY_QUOTA:-1}"
export QLORA_DPO_V2D_TRUE_REASON_AUX_QUOTA="${QLORA_DPO_V2D_TRUE_REASON_AUX_QUOTA:-1}"
export QLORA_DPO_V2D_TRUE_HEAD_FALLBACK_QUOTA="${QLORA_DPO_V2D_TRUE_HEAD_FALLBACK_QUOTA:-1}"
export QLORA_DPO_V2D_TRUE_BOUNDARY_FALLBACK_QUOTA="${QLORA_DPO_V2D_TRUE_BOUNDARY_FALLBACK_QUOTA:-1}"
export QLORA_DPO_V2D_TRUE_MID_FALLBACK_QUOTA="${QLORA_DPO_V2D_TRUE_MID_FALLBACK_QUOTA:-1}"
export QLORA_DPO_V2D_TRUE_DEEP_FALLBACK_QUOTA="${QLORA_DPO_V2D_TRUE_DEEP_FALLBACK_QUOTA:-1}"
export QLORA_DPO_V2D_VALID_BOUNDARY_RESCUE_QUOTA="${QLORA_DPO_V2D_VALID_BOUNDARY_RESCUE_QUOTA:-0}"
export QLORA_DPO_V2D_VALID_COMPETITION_QUOTA="${QLORA_DPO_V2D_VALID_COMPETITION_QUOTA:-0}"
export QLORA_DPO_V2D_VALID_FIT_RISK_QUOTA="${QLORA_DPO_V2D_VALID_FIT_RISK_QUOTA:-0}"
export QLORA_DPO_V2D_VALID_SEMANTIC_QUOTA="${QLORA_DPO_V2D_VALID_SEMANTIC_QUOTA:-0}"
export QLORA_DPO_MULTI_ROUTE_PRESERVE_SOURCE_EDGE_MIN="${QLORA_DPO_MULTI_ROUTE_PRESERVE_SOURCE_EDGE_MIN:-2}"
export QLORA_DPO_RESCUE_31_60_PRIMARY_BLOCKER_MIN_RANK="${QLORA_DPO_RESCUE_31_60_PRIMARY_BLOCKER_MIN_RANK:-21}"
export QLORA_DPO_RESCUE_31_60_PRIMARY_BLOCKER_MAX_RANK="${QLORA_DPO_RESCUE_31_60_PRIMARY_BLOCKER_MAX_RANK:-30}"
export QLORA_DPO_RESCUE_31_60_SECONDARY_BLOCKER_MIN_RANK="${QLORA_DPO_RESCUE_31_60_SECONDARY_BLOCKER_MIN_RANK:-7}"
export QLORA_DPO_RESCUE_31_60_SECONDARY_BLOCKER_MAX_RANK="${QLORA_DPO_RESCUE_31_60_SECONDARY_BLOCKER_MAX_RANK:-20}"
export QLORA_DPO_RESCUE_31_60_NEG_RANK_MAX="${QLORA_DPO_RESCUE_31_60_NEG_RANK_MAX:-30}"
export QLORA_DPO_RESCUE_61_100_NEG_RANK_MAX="${QLORA_DPO_RESCUE_61_100_NEG_RANK_MAX:-50}"

echo "[INFO] bucket5 stage11 semantic_compact_boundary_rm export-only"
echo "[INFO] repo=${REPO_ROOT}"
echo "[INFO] input_11=${INPUT_11_RUN_DIR}"
echo "[INFO] input_09=${INPUT_09_RUN_DIR}"
echo "[INFO] output_11_pairwise=${OUTPUT_11_PAIRWISE_ROOT_DIR}"
echo "[INFO] prompt_mode=${QLORA_PROMPT_MODE}"
echo "[INFO] target_true_bands=${QLORA_TARGET_TRUE_BANDS}"
echo "[INFO] pair_policy=${QLORA_DPO_PAIR_POLICY}"
echo "[INFO] pair_prompt_style=${QLORA_PAIR_PROMPT_STYLE}"
echo "[INFO] dpo_true_max_pairs=${QLORA_DPO_TRUE_MAX_PAIRS}"
echo "[INFO] spark_master=${SPARK_MASTER} shuffle=${SPARK_SQL_SHUFFLE_PARTITIONS} parallelism=${SPARK_DEFAULT_PARALLELISM}"
echo "[INFO] v2d_mid_same_band_quota.true=${QLORA_DPO_V2D_TRUE_MID_SAME_BAND_QUOTA}"
echo "[INFO] v2d_mid_slate_variants.true=${QLORA_DPO_V2D_TRUE_MID_SLATE_VARIANTS}"
echo "[INFO] v2d_mid_explicit_slate_types=${QLORA_DPO_V2D_TRUE_MID_EXPLICIT_SLATE_TYPES}"
echo "[INFO] freeze_boundary_11_30_v1=${QLORA_DPO_FREEZE_BOUNDARY_11_30_V1}"
echo "[INFO] v2d_mid_generic_fill=${QLORA_DPO_V2D_MID_GENERIC_FILL}"
echo "[INFO] v2d_deep_same_band_quota.true=${QLORA_DPO_V2D_TRUE_DEEP_SAME_BAND_QUOTA}"
echo "[INFO] v2d_deep_mid_band_quota.true=${QLORA_DPO_V2D_TRUE_DEEP_MID_BAND_QUOTA}"
echo "[INFO] v2d_deep_boundary_quota.true=${QLORA_DPO_V2D_TRUE_DEEP_BOUNDARY_QUOTA}"
echo "[INFO] v2d_deep_head_quota.true=${QLORA_DPO_V2D_TRUE_DEEP_HEAD_QUOTA}"
echo "[INFO] v2d_deep_slate_variants.true=${QLORA_DPO_V2D_TRUE_DEEP_SLATE_VARIANTS}"
echo "[INFO] v2d_deep_explicit_slate_types=${QLORA_DPO_V2D_TRUE_DEEP_EXPLICIT_SLATE_TYPES}"
echo "[INFO] v2d_deep_variant_fallback_fill=${QLORA_DPO_V2D_TRUE_DEEP_VARIANT_FALLBACK_FILL}"
echo "[INFO] v2d_deep_allow_cross_variant_reuse=${QLORA_DPO_V2D_TRUE_DEEP_ALLOW_CROSS_VARIANT_REUSE} cap=${QLORA_DPO_V2D_TRUE_DEEP_CROSS_VARIANT_REUSE_CAP}"
echo "[INFO] v2d_deep_relax_actionability=${QLORA_DPO_V2D_TRUE_DEEP_RELAX_ACTIONABILITY} min_signal=${QLORA_DPO_V2D_TRUE_DEEP_RELAX_MIN_SIGNAL_COUNT}"
echo "[INFO] v2d_head_guard_quota.true=${QLORA_DPO_V2D_TRUE_HEAD_PRESERVE_QUOTA}"
echo "[INFO] v2d_boundary_rescue_quota.true=${QLORA_DPO_V2D_TRUE_BOUNDARY_RESCUE_QUOTA}"
echo "[INFO] v2d_multi_route_rescue_quota.true=${QLORA_DPO_V2D_TRUE_MULTI_ROUTE_RESCUE_QUOTA}"
echo "[INFO] rescue_31_60_blockers.primary=${QLORA_DPO_RESCUE_31_60_PRIMARY_BLOCKER_MIN_RANK}-${QLORA_DPO_RESCUE_31_60_PRIMARY_BLOCKER_MAX_RANK} secondary=${QLORA_DPO_RESCUE_31_60_SECONDARY_BLOCKER_MIN_RANK}-${QLORA_DPO_RESCUE_31_60_SECONDARY_BLOCKER_MAX_RANK}"
echo "[INFO] v2d_reason_primary_quota.true=${QLORA_DPO_V2D_TRUE_REASON_PRIMARY_QUOTA}"
echo "[INFO] v2d_reason_aux_quota.true=${QLORA_DPO_V2D_TRUE_REASON_AUX_QUOTA}"
echo "[INFO] v2d_valid_boundary_rescue_quota=${QLORA_DPO_V2D_VALID_BOUNDARY_RESCUE_QUOTA}"

"${PYTHON_BIN}" "${REPO_ROOT}/scripts/11_2_dpo_export_pairs.py"
