#!/usr/bin/env bash
set -euo pipefail
# Legacy compatibility launcher. Prefer scripts/launchers/stage11_bucket5_11_1.sh.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
source "${SCRIPT_DIR}/../launchers/_path_contract.sh"
PYTHON_BIN="${PYTHON_BIN:-}"
if [[ -z "${PYTHON_BIN}" ]]; then
  if command -v python3 >/dev/null 2>&1; then
    PYTHON_BIN="$(command -v python3)"
  elif command -v python >/dev/null 2>&1; then
    PYTHON_BIN="$(command -v python)"
  elif [[ -x "${BDA_REMOTE_PYTHON_BIN}" ]]; then
    PYTHON_BIN="${BDA_REMOTE_PYTHON_BIN}"
  else
    echo "[ERROR] python executable not found" >&2
    exit 1
  fi
fi

export PYSPARK_PYTHON="${PYSPARK_PYTHON:-${PYTHON_BIN}}"
export PYSPARK_DRIVER_PYTHON="${PYSPARK_DRIVER_PYTHON:-${PYTHON_BIN}}"

INPUT_09_RUN_DIR="${INPUT_09_RUN_DIR:-${BDA_REMOTE_PROJECT_OUTPUT_ROOT}/09_candidate_fusion_structural_v5_sourceparity/20260324_030511_full_stage09_candidate_fusion}"
INPUT_10_ROOT_DIR="${INPUT_10_ROOT_DIR:-${BDA_REMOTE_PROJECT_OUTPUT_ROOT}/10_2_rank_infer_eval_joint_min_cls_v5_typed_intent_phase3_slicefix}"
INPUT_10_RUN_DIR="${INPUT_10_RUN_DIR:-${BDA_REMOTE_FAST_ROOT}/bucket5_stage10_phase3_fullcohort_learned/output/10_2_rank_infer_eval_joint_min_cls_v5_typed_intent_phase3_slicefix_fullcohort/20260330_024735_stage10_2_rank_infer_eval}"
INPUT_10_13_RESCUE_AUDIT_RUN_DIR="${INPUT_10_13_RESCUE_AUDIT_RUN_DIR:-${BDA_REMOTE_FAST_ROOT}/bucket5_stage11_reason_audit_phase3_fullcohort/20260330_stage11_reason_audit_fullcohort}"
INPUT_09_MATCH_CHANNELS_RUN_DIR="${INPUT_09_MATCH_CHANNELS_RUN_DIR:-${BDA_REMOTE_PROJECT_OUTPUT_ROOT}/09_user_business_match_channels_v2_bucket5_sourceparity/20260325_233813_full_stage09_user_business_match_split_aware_v2_build}"
INPUT_09_STAGE11_SEMANTIC_TEXT_ASSETS_V1_ROOT_DIR="${INPUT_09_STAGE11_SEMANTIC_TEXT_ASSETS_V1_ROOT_DIR:-${BDA_REMOTE_PROJECT_OUTPUT_ROOT}/09_stage11_semantic_text_assets_v1}"
INPUT_09_STAGE11_SEMANTIC_TEXT_ASSETS_V1_RUN_DIR="${INPUT_09_STAGE11_SEMANTIC_TEXT_ASSETS_V1_RUN_DIR:-}"
FIXED_COHORT_PATH="${FIXED_COHORT_PATH:-${REPO_ROOT}/data/output/fixed_eval_cohorts/bucket5_accepted_test_users_1935_userid.csv}"
SPARK_LOCAL_DIR_DEFAULT="${REPO_ROOT}/data/spark-tmp"
OUTPUT_11_DATA_ROOT_DIR="${OUTPUT_11_DATA_ROOT_DIR:-${BDA_REMOTE_FAST_ROOT}/bucket5_top250_semantic_compact_boundary_reason_rm_11_1/output/11_qlora_data}"

mkdir -p "${OUTPUT_11_DATA_ROOT_DIR}" "${SPARK_LOCAL_DIR_DEFAULT}"

export BDA_PROJECT_ROOT="${REPO_ROOT}"
export INPUT_09_RUN_DIR
export INPUT_10_ROOT_DIR
export INPUT_10_RUN_DIR
export INPUT_10_13_RESCUE_AUDIT_RUN_DIR
export INPUT_09_MATCH_CHANNELS_RUN_DIR
export INPUT_09_STAGE11_SEMANTIC_TEXT_ASSETS_V1_ROOT_DIR
export INPUT_09_STAGE11_SEMANTIC_TEXT_ASSETS_V1_RUN_DIR
export OUTPUT_11_DATA_ROOT_DIR
export BUCKETS_OVERRIDE="${BUCKETS_OVERRIDE:-5}"

export SPARK_MASTER="${SPARK_MASTER:-local[24]}"
export SPARK_DRIVER_MEMORY="${SPARK_DRIVER_MEMORY:-76g}"
export SPARK_EXECUTOR_MEMORY="${SPARK_EXECUTOR_MEMORY:-76g}"
export SPARK_LOCAL_DIR="${SPARK_LOCAL_DIR:-${SPARK_LOCAL_DIR_DEFAULT}}"
export SPARK_SQL_SHUFFLE_PARTITIONS="${SPARK_SQL_SHUFFLE_PARTITIONS:-192}"
export SPARK_DEFAULT_PARALLELISM="${SPARK_DEFAULT_PARALLELISM:-192}"
export SPARK_SQL_CONSTRAINT_PROPAGATION_ENABLED="${SPARK_SQL_CONSTRAINT_PROPAGATION_ENABLED:-false}"
export SPARK_NETWORK_TIMEOUT="${SPARK_NETWORK_TIMEOUT:-1200s}"
export SPARK_EXECUTOR_HEARTBEAT_INTERVAL="${SPARK_EXECUTOR_HEARTBEAT_INTERVAL:-120s}"
export SPARK_DRIVER_HOST="${SPARK_DRIVER_HOST:-127.0.0.1}"
export SPARK_DRIVER_BIND_ADDRESS="${SPARK_DRIVER_BIND_ADDRESS:-127.0.0.1}"
export SPARK_TMP_SESSION_ISOLATION="${SPARK_TMP_SESSION_ISOLATION:-true}"
export SPARK_TMP_AUTOCLEAN_ENABLED="${SPARK_TMP_AUTOCLEAN_ENABLED:-false}"
export SPARK_TMP_CLEAN_ON_EXIT="${SPARK_TMP_CLEAN_ON_EXIT:-true}"
export SPARK_TMP_RETENTION_HOURS="${SPARK_TMP_RETENTION_HOURS:-8}"
export SPARK_TMP_CLEAN_MAX_ENTRIES="${SPARK_TMP_CLEAN_MAX_ENTRIES:-3000}"
export PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-true}"

export QLORA_ENFORCE_STAGE09_GATE="${QLORA_ENFORCE_STAGE09_GATE:-true}"
export QLORA_GATE_MIN_TRUTH_IN_PRETRIM="${QLORA_GATE_MIN_TRUTH_IN_PRETRIM:-0.74}"
export QLORA_GATE_MAX_PRETRIM_CUT_LOSS="${QLORA_GATE_MAX_PRETRIM_CUT_LOSS:-0.14}"
export QLORA_GATE_MAX_HARD_MISS="${QLORA_GATE_MAX_HARD_MISS:-0.12}"

export TRAIN_CANDIDATE_FILE="${TRAIN_CANDIDATE_FILE:-candidates_pretrim.parquet}"
export QLORA_TOPN_PER_USER="${QLORA_TOPN_PER_USER:-250}"
export QLORA_ENABLE_RICH_SFT_EXPORT="${QLORA_ENABLE_RICH_SFT_EXPORT:-false}"
export QLORA_ENABLE_PAIRWISE_POOL_EXPORT="${QLORA_ENABLE_PAIRWISE_POOL_EXPORT:-true}"
export QLORA_PAIRWISE_POOL_TOPN="${QLORA_PAIRWISE_POOL_TOPN:-100}"
export QLORA_PAIRWISE_POOL_MINIMAL_EXPORT="${QLORA_PAIRWISE_POOL_MINIMAL_EXPORT:-true}"
export QLORA_TRAIN_SOURCE="${QLORA_TRAIN_SOURCE:-pairwise_pool}"
export QLORA_ITEM_EVIDENCE_SCORE_UDF_MODE="${QLORA_ITEM_EVIDENCE_SCORE_UDF_MODE:-pandas}"
export QLORA_PROMPT_MODE="${QLORA_PROMPT_MODE:-semantic_compact_boundary_rm}"
export QLORA_ATTACH_STAGE10_TEXT_MATCH="${QLORA_ATTACH_STAGE10_TEXT_MATCH:-true}"
export QLORA_ATTACH_STAGE10_GROUP_GAP="${QLORA_ATTACH_STAGE10_GROUP_GAP:-true}"
export QLORA_ATTACH_STAGE10_MATCH_CHANNELS="${QLORA_ATTACH_STAGE10_MATCH_CHANNELS:-true}"
export QLORA_ATTACH_STAGE10_LEARNED="${QLORA_ATTACH_STAGE10_LEARNED:-true}"
export QLORA_ATTACH_STAGE11_RESCUE_REASON="${QLORA_ATTACH_STAGE11_RESCUE_REASON:-true}"
export QLORA_DATASET_EVAL_USER_COHORT_PATH="${QLORA_DATASET_EVAL_USER_COHORT_PATH:-${FIXED_COHORT_PATH}}"
export QLORA_MAX_SEQ_LEN="${QLORA_MAX_SEQ_LEN:-1024}"
export QLORA_MAX_ROWS_PER_BUCKET="${QLORA_MAX_ROWS_PER_BUCKET:-0}"
export QLORA_WRITE_JSON_PARTITIONS="${QLORA_WRITE_JSON_PARTITIONS:-1}"
export QLORA_WRITE_PARQUET_PARTITIONS="${QLORA_WRITE_PARQUET_PARTITIONS:-24}"
export QLORA_WRITE_AUX_PARTITIONS="${QLORA_WRITE_AUX_PARTITIONS:-4}"
export QLORA_INCLUDE_VALID_POS="${QLORA_INCLUDE_VALID_POS:-true}"
export QLORA_VALID_POS_WEIGHT="${QLORA_VALID_POS_WEIGHT:-0.25}"
export QLORA_VALID_POS_ONLY_IF_NO_TRUE="${QLORA_VALID_POS_ONLY_IF_NO_TRUE:-true}"
export QLORA_RICH_SFT_NEG_EXPLICIT="${QLORA_RICH_SFT_NEG_EXPLICIT:-1}"
export QLORA_RICH_SFT_NEG_HARD="${QLORA_RICH_SFT_NEG_HARD:-3}"
export QLORA_RICH_SFT_NEG_NEAR="${QLORA_RICH_SFT_NEG_NEAR:-2}"
export QLORA_RICH_SFT_NEG_MID="${QLORA_RICH_SFT_NEG_MID:-2}"
export QLORA_RICH_SFT_NEG_TAIL="${QLORA_RICH_SFT_NEG_TAIL:-1}"
export QLORA_RICH_SFT_ALLOW_NEG_FILL="${QLORA_RICH_SFT_ALLOW_NEG_FILL:-true}"

export QLORA_SKIP_POINTWISE_EXPORT="${QLORA_SKIP_POINTWISE_EXPORT:-true}"
export QLORA_SKIP_RICH_SFT_JSON_EXPORT="${QLORA_SKIP_RICH_SFT_JSON_EXPORT:-true}"
export QLORA_SKIP_PAIRWISE_POOL_JSON_EXPORT="${QLORA_SKIP_PAIRWISE_POOL_JSON_EXPORT:-true}"
export QLORA_ENABLE_HEAVY_STAGE_CHECKPOINTS="${QLORA_ENABLE_HEAVY_STAGE_CHECKPOINTS:-true}"
export QLORA_HEAVY_STAGE_CHECKPOINT_EAGER="${QLORA_HEAVY_STAGE_CHECKPOINT_EAGER:-true}"
export QLORA_PAIRWISE_POOL_WRITE_PARQUET_PARTITIONS="${QLORA_PAIRWISE_POOL_WRITE_PARQUET_PARTITIONS:-16}"

echo "[INFO] bucket5 stage11 top250 semantic_compact_boundary_rm 11_1 launcher"
echo "[INFO] repo=${REPO_ROOT}"
echo "[INFO] source_stage09=${INPUT_09_RUN_DIR}"
echo "[INFO] source_stage10_root=${INPUT_10_ROOT_DIR}"
echo "[INFO] source_stage10_run=${INPUT_10_RUN_DIR:-<latest under root>}"
echo "[INFO] source_stage10_13_rescue_reason=${INPUT_10_13_RESCUE_AUDIT_RUN_DIR:-<latest under root>}"
echo "[INFO] source_stage09_match_channels_run=${INPUT_09_MATCH_CHANNELS_RUN_DIR:-<latest under root>}"
echo "[INFO] source_stage09_stage11_semantic_text_assets_root=${INPUT_09_STAGE11_SEMANTIC_TEXT_ASSETS_V1_ROOT_DIR}"
echo "[INFO] source_stage09_stage11_semantic_text_assets_run=${INPUT_09_STAGE11_SEMANTIC_TEXT_ASSETS_V1_RUN_DIR:-<latest under root>}"
echo "[INFO] fixed_cohort=${FIXED_COHORT_PATH}"
echo "[INFO] python=${PYTHON_BIN}"
echo "[INFO] prompt_mode=${QLORA_PROMPT_MODE}"
echo "[INFO] enable_rich_sft_export=${QLORA_ENABLE_RICH_SFT_EXPORT} enable_pairwise_pool_export=${QLORA_ENABLE_PAIRWISE_POOL_EXPORT}"
echo "[INFO] train_source=${QLORA_TRAIN_SOURCE} pairwise_pool_topn=${QLORA_PAIRWISE_POOL_TOPN} pairwise_pool_minimal_export=${QLORA_PAIRWISE_POOL_MINIMAL_EXPORT}"
echo "[INFO] enforce_stage09_gate=${QLORA_ENFORCE_STAGE09_GATE}"
echo "[INFO] spark_master=${SPARK_MASTER} shuffle=${SPARK_SQL_SHUFFLE_PARTITIONS} parallelism=${SPARK_DEFAULT_PARALLELISM}"
echo "[INFO] heavy_stage_checkpoints=${QLORA_ENABLE_HEAVY_STAGE_CHECKPOINTS} eager=${QLORA_HEAVY_STAGE_CHECKPOINT_EAGER}"

"${PYTHON_BIN}" "${REPO_ROOT}/scripts/11_1_qlora_build_dataset.py"
