#!/usr/bin/env bash
# Shared path anchors for active compatibility launchers.
# Default expansions intentionally preserve the current remote/local layout.

if [[ -n "${BDA_PATH_CONTRACT_LOADED:-}" ]]; then
  return 0
fi
export BDA_PATH_CONTRACT_LOADED=1

export BDA_REMOTE_TMP_ROOT="${BDA_REMOTE_TMP_ROOT:-/root/autodl-tmp}"
export BDA_REMOTE_PROJECT_ROOT="${BDA_REMOTE_PROJECT_ROOT:-${BDA_REMOTE_TMP_ROOT}/5006_BDA_project}"
export BDA_REMOTE_PROJECT_DATA_ROOT="${BDA_REMOTE_PROJECT_DATA_ROOT:-${BDA_REMOTE_PROJECT_ROOT}/data}"
export BDA_REMOTE_PROJECT_OUTPUT_ROOT="${BDA_REMOTE_PROJECT_OUTPUT_ROOT:-${BDA_REMOTE_PROJECT_DATA_ROOT}/output}"
export BDA_REMOTE_PROJECT_SPARK_TMP_ROOT="${BDA_REMOTE_PROJECT_SPARK_TMP_ROOT:-${BDA_REMOTE_PROJECT_DATA_ROOT}/spark-tmp}"
export BDA_REMOTE_FAST_ROOT="${BDA_REMOTE_FAST_ROOT:-${BDA_REMOTE_TMP_ROOT}/5006_BDA_fast}"
export BDA_REMOTE_HF_ROOT="${BDA_REMOTE_HF_ROOT:-/root/hf_models}"
export BDA_REMOTE_PYTHON_BIN="${BDA_REMOTE_PYTHON_BIN:-/root/miniconda3/bin/python}"

export BDA_REMOTE_AUTODL_FS_ROOT="${BDA_REMOTE_AUTODL_FS_ROOT:-/autodl-fs/data/5006_BDA_project_work}"
export BDA_REMOTE_AUTODL_FS_DATA_ROOT="${BDA_REMOTE_AUTODL_FS_DATA_ROOT:-${BDA_REMOTE_AUTODL_FS_ROOT}/data}"
export BDA_REMOTE_AUTODL_FS_OUTPUT_ROOT="${BDA_REMOTE_AUTODL_FS_OUTPUT_ROOT:-${BDA_REMOTE_AUTODL_FS_DATA_ROOT}/output}"
export BDA_REMOTE_AUTODL_FS_SCRIPTS_ROOT="${BDA_REMOTE_AUTODL_FS_SCRIPTS_ROOT:-${BDA_REMOTE_AUTODL_FS_ROOT}/scripts}"
